# FIXME - We should probably pull directly from the forge
mod 'inifile',  '0.0.1', :github_tarball => 'boxen/puppet-inifile'
mod 'boxen',    '0.1.8', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew', '0.2.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',   '3.0.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'module-data', '0.0.1', :github_tarball => 'ripienaar/puppet-module-data'
