# FIXME - We should probably pull directly from the forge
mod 'inifile',     '1.4.2',  :github_tarball => 'puppetlabs/puppetlabs-inifile'
mod 'boxen',       '3.11.0', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew',    '1.13.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',      '4.9.0',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'module-data', '0.0.1',  :github_tarball => 'ripienaar/puppet-module-data'
