mod 'inifile',  '1.0.3', :github_tarball => 'puppetlabs/puppetlabs-inifile'
mod 'boxen',    '3.6.1', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew', '1.9.2', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',   '4.2.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
